### ISSUE TITLE
afew silently dying in cronjobs?

### ISSUE THREAD

**Issue by pazz** [afewmail/afew#100]
This might be a problem specific to my setup (fresh debian testing, python 2.7.8), but I thought I'd give it a go here..

I have a script that pulls mails, and calls notmuch and afew, roughtly as below.

```
#!/bin/bash

# look up pid of running gnome-keyring-daemon to unlock passwds

die() { 
    # notify me about error via desktop notifications
    exit 1
}

index() {
    echo ------------------------ NOTMUCH ------------------------
    /usr/local/bin/notmuch new || die "NOTMUCH new failed"

    echo ------------------------  AFEW   ------------------------
    /home/pazz/.local/bin/afew -v -t -n -C /home/pazz/.notmuch-config
    echo ---------------------------------------------------------
}


set -e
nm-online -x   # stop if not online

/usr/bin/mbsync $@ uow || die "UOW failed"
/usr/bin/mbsync $@ gmail || die "GMAIL failed"

index
date
```

Works fine when triggered manually. In particular, I get afew's verbose log
messages.
Now when I call this script from cron, it seems that afew is not called at all:

On standart out I get:

```
...
------------------------ NOTMUCH ------------------------
Processed 42 total files in almost no time.
No new mail.
------------------------ AFEW ------------------------
----------------------------------------------------------
Sat 14 Feb 14:52:09 GMT 2015
```

First question: why does `afew -v` print to stderr, and not to stdout?
Secondly, even the standart err contains nothing of afew:
i get some notmuch error messages complaining about nonmail (mbsync status) files,
but no output from afew.

Also, afew seems not to have run: new messages carry the `new` tag and are not tagged otherwise.
It seems afew died silently on me.
Any suggestions?

[edit] and by "silently", i mean not doing anything while still exiting with return code 0.

**Comment by pazz** [comment]
to answer my first question: afew uses the `logging` module and that prints to stderr per default.

I added some "print()"'s to afew for the heck of it. And it seems afew does in fact run and also exit properly when called by cron. It seems that it just can't find any filters and thus doesn't do anything..

**Comment by pazz** [comment]
some more debugging:

It seems that this line: https://github.com/teythoon/afew/blob/master/afew/Settings.py#L36
does not what it's supposed to:

The value of `user_config_dir` before is:
```
 /home/pazz/.config/afew/config
```

afterwards, `settings.sections()` returns

```
['global', 'SpamFilter', 'KillThreadsFilter',  ...]
```

according to my config, when I call afew from the terminal.
From cron, `settings.sections()` returns

```
['global']
```

I thought it was an issue with file permissions for this file, but a crontab entry

```
* * * * * cat /home/pazz/.config/afew/config >/home/pazz/.afew.slog
```

has the effect that the config file is copied as expected.
Now I'm really at my wits' end :/

**Comment by pazz** [comment]
ARGS!

The value of `user_config_dir` was in fact
```
$HOME/.config/afew
```

The patch below fixes the issue for me. Do you have any reservations agains
`os.path.expandvars` at this point?

```
+++ b/afew/Settings.py
@@ -27,6 +27,7 @@ from afew.FilterRegistry import all_filters
 user_config_dir = os.path.join(os.environ.get('XDG_CONFIG_HOME',
                                               os.path.expanduser('~/.config')),
                                'afew')
+user_config_dir=os.path.expandvars(user_config_dir)
 
 settings = SafeConfigParser()
 # preserve the capitalization of the keys.

```

**Comment by teythoon** [comment]
Hi Pazz :)

Quoting Patrick Totzke (2015-02-20 01:21:24)
> $HOME/.config/afew
> 
> The patch below fixes the issue for me. Do you have any reservations agains
> os.path.expandvars at this point?

:/ good catch.  I don't have reservations against your patch.  I'm
somewhat curious though where the `$HOME/.config/afew' came from.

Justus

**Comment by pazz** [comment]
Sidenote: when I fumbled around with this i saw that afew has a `-C` option to set notmuchs config
but no option to set its own. This would have allowed to fix the issue without sending patches..
