### ISSUE TITLE
Multiline querys in config file

### ISSUE THREAD

**Issue by jfeick** [afewmail/afew#122]
The config file does not allow querys that span more than one line.

Example:
```
[MailMover]
folders = INBOX
INBOX = 'tag:sometag OR
         from:someone@somedomain.com OR
         subject:somesubject':DestinationDir
```

Changing line 80 in Settings.py to use the flag `re.DOTALL` would allow this behaviour to construct querys over multiple lines without breaking existing configuration files:

**Settings.py**
```
80:    rule_pattern = re.compile(r"'(.+?)':(\S+)", re.DOTALL)
```

**Comment by GuillaumeSeren** [comment]
Hey @jfeick 
This is unusual, but I think this could be nice to have, how about making a PR to change that settings.
But it is nice to share that 🍺

**Comment by GuillaumeSeren** [comment]
I close this issue, the next step would be a PR if possible !
