### ISSUE TITLE
Project state & future

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#125]
Hey afew users and maintainers !

I have been a happy, afew user since I moved to notmuch, it helped me really well,
mainly moving mail, and tagging news and mailing list.
Since I got 'a lot' (no joke 😃) of work everyday done by afew,I am quite concern by the fact that the project seems to have stopped movement since (2016-02-29 b19a88f) which is 10 month before.
At the time writing this issue there is 13 open pull request, so I am wondering
* Does the project is actually paused, or the author need some help ?
* Does the user-base is leaving to something else, in that case I am open for suggestions.

Thank you for reading, and hoping this issue will help somehow.

**Comment by teythoon** [comment]
Thanks for bringing it up.  I'd love to see afew used and developed, but I no longer want to maintain it.  I'd be happy to hand over the project to someone, or preferably a group of people.

**Comment by lucc** [comment]
There has recently been a discussion about the future development of development (pun intended) for alot: https://github.com/pazz/alot/issues/908

Maybe you can find a similar group of people here (or even ask the alot people if some are intereseted).

**Comment by GuillaumeSeren** [comment]
@lucc Yes this discussion motivate me to start this issue 😃 

@teythoon We can ping each active devs on the project / fork to form a group,
at least there is a user base, so we just need to gather them here, and try to organise some objectives.

**Comment by flokli** [comment]
@GuillaumeSeren, @lucc: I could also help out here, as I use afew a lot, and also have some things bugging me. Unfortunately, with my PR laying around for a long time, I wasn't quite motivated to do more so far.

If @teythoon is okay with it, I'd be happy to review outstanding PRs with some of the active developers. Later, we could move this to a new organization.

**Comment by GuillaumeSeren** [comment]
@flokli Hey,
I agree that having an organisation could help, or just promoting some active users, maybe we can do that to encourage people review code, and help with PR.

I think, we need to build a planning / todo list to be able to show where we need manpower, and try to cut release (even small) more often, we also need to figure out if the waiting PR are viable and so merge them, or close them.

**Comment by flokli** [comment]
@GuillaumeSeren: @teythoon pointed out he doesn't want to maintain the project anymore. I'd be happy to take a look at those open PR, and merge them if possible.

@teythoon: Could you hand over access to me and @GuillaumeSeren, if he's okay with that? We could then decide about moving this into a separate github organization.

**Comment by GuillaumeSeren** [comment]
@flokli I agree creating a group that help the project is the good path to me.

**Comment by freeekanayaka** [comment]
Hey there, I'm an active afew user as well and would like to help with maintaining it (e.g. reviewing PRs).

I've packaged it for Debian [0] and I'm somehow familiar with the code (which is actually quite simple). I'd like to be included in the new organization, whenever (and if) it gets created.

Happy new year!

[0] https://packages.debian.org/search?keywords=afew

**Comment by fnurl** [comment]
I've recently started to use alot and notmuch together with [gauteh/abunchoftags](https://github.com/gauteh/abunchoftags), but have held off trying to use afew because of the lack updates. `afew` seems like a good solution to automatic tagging, so I hope the project can be revitalized.

**Comment by mkaito** [comment]
Hey there!

Active afew user here, would also like to be of help.

**Comment by andir** [comment]
If there is help required I'm willing to step in.

**Comment by flokli** [comment]
Awesome, seems like there are a lot of people willing to help!

@teythoon Could you hand over access to the repo, so we can move it into a new organization?

**Comment by teythoon** [comment]
I did add you to the project as collaborators, is that ok?  Feel free to add other people, we can also transfer the project somewhere else.  Thanks for stepping up.  Thanks for packaging it.

**Comment by freeekanayaka** [comment]
@teythoon it doesn't seem I have write access to the repo, fwiw.

I think I new org would be a bit better, my 2c.

**Comment by flokli** [comment]
I creaded a new organization [afewmail](github.com/afewmail) (afew is already taken by a username) and added everyone who wanted to help taking over the project. Please tell me in case I forgot someone.

Next step would be to move the repo inside this organization.

@teythoon Can you do this, or grant us permission?

**Comment by GuillaumeSeren** [comment]
Thanks @teythoon for the invite !

**Comment by teythoon** [comment]
@flokli sure, I would, but I don't know how to grant you that permission.  It seems that I could transfer the project to the organization you created if I would be a contributor there.  Could you add me so that I can transfer it?

**Comment by flokli** [comment]
@teythoon You are now a member of the new `afewmail` organization, should have received an email. Can you try to transfer the repo to there?

**Comment by teythoon** [comment]
@flokli done!  Thanks for all the future fish :)

**Comment by flokli** [comment]
Moved, thanks! I will close this issue now :-)
