### ISSUE TITLE
Labels and sorting PR

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#126]
Hey,
I have started to create some label, but I assume it should be discussed what / how we need exactly,
I think labels, are an easy way to add a small value to the PR, and let people know we are checking it.

This will help organising the stream of PR, and we can decide of some more complex validation process later (tests), but it is a good tool to see the state of open PR.

The list I suggest (it divide basically on 2 theme good / bad thing)

- doc
- duplicate
- bug
- enhancement
- fix
- waiting-reply

What do you think ?

**Comment by flokli** [comment]
I'd suggest to throw `needs-rework` and `reviewed` into the mix, to easily filter in-progress pull requests, but apart from that, LGTM.

**Comment by GuillaumeSeren** [comment]
@flokli Ok !

**Comment by flokli** [comment]
@GuillaumeSeren Can you do some initial labelling on the current list of issues? This might help in getting the list of open issues and PRs smaller, and probably wake up some people :-)

**Comment by GuillaumeSeren** [comment]
@flokli Yes I started that, it is quite some work to do, so it should take some time to do them all.

**Comment by flokli** [comment]
@GuillaumeSeren Thanks for your work and comments on all the issues during the day, I really appreciate it! Will have a look at them soon!

**Comment by GuillaumeSeren** [comment]
I am adding use-case flag, to describe unusual usage

**Comment by GuillaumeSeren** [comment]
Let's close this issue
