### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#129]
Hey !
As stated in #125 @teythoon is retiring from the maintenance of the project,
so he agreed to let the project to be more maintained by active volunteer from the community.

So now is a good time to cut a release, it was asked at least in #53, and #83 and before we start merging things, marking the transition and also some thanks to this great tool I use everyday.

So my proposal, is to tag a v1 named "teythoon" and to do it asap before any changes.

**Comment by andir** [comment]
That sounds like a good idea. Lets do it 👍

**Comment by bfontaine** [comment]
It’d be great if you could make it as a version, e.g. `v1-theythoon` so that from a tag name we know which version it refers to.

**Comment by GuillaumeSeren** [comment]
@bfontaine Yes it is the idea, I think call it a 1.0 and add a codename (alias) in the tag commit would be enough.

@mkaito @freeekanayaka @flokli @andir Are you agree ?

**Comment by freeekanayaka** [comment]
@GuillaumeSeren that works for me, thanks for asking!

My preferred approach would be to use a semantic version <MAJOR>.<MINOR>.<PATCH> (e.g. "1.0.0" or "v1.0.0") as name of the tag, and sign the tag with a GPG key, with a message like "Codename teythoon", e.g.:

git tag -s -m "Codename teythoon" 1.0.0

The message will be displayed by GitHub too.

Also, we should push this release to PyPI (I can take care of that if needed).

**Comment by GuillaumeSeren** [comment]
@freeekanayaka Yes totally agree since the codename is in the commit title we do not need it in the tag name itself.
And yes I will sign it with my gpg key, good idea ! 

If you want to help for ht PyPI package have a look at #83

**Comment by flokli** [comment]
I also agree with @freeekanayaka, let's put the 'codename' in the commit message.

However, we probably should start with a lower version number, as there is still a milestone for v0.1 defined.

So I'd vote for 
```git tag -s -m "Codename teythoon" v0.0.9```

**Comment by freeekanayaka** [comment]
@GuillaumeSeren sure, if nobody steps in I'll do a pypi upload after the release.

There's no "afew" package in PyPI yet, so assuming I'll be the one doing the upload I'll become the owner of it. I'd be good if I was not the only owner, so for the ones that have a PyPI account, please let me know it and I'll add you as owners.

**Comment by GuillaumeSeren** [comment]
@flokli Yes we could use a lower version number, but as the project is quite known and nearly 6 years old, I think it is wide used in the notmuch community and a 1.0.0 correspond better to it's actual state and usage, and it is also a good way to mark the switching of maintainer(s).

I stand for the 1.0.0 !

**Comment by freeekanayaka** [comment]
@GuillaumeSeren +1 from me (re 1.0.0)

**Comment by freeekanayaka** [comment]
It should be too hard to maintain backward compatibility, so 1.0.0 it's not a stretch. If we really need to break backward compatibility later at some point (and provide some upgrade script/path), we can release 2.0.0.

**Comment by flokli** [comment]
Well, so let's call it 1.0.0, and rename the milestone :-D

@GuillaumeSeren: I also have a PyPi account (flokli there too), you can add me as an owner for the PyPi package, too :-)

**Comment by mkaito** [comment]
I agree as well. Sign a tag with semantic versioning. Then put the codename in the signature and commit message.

**Comment by GuillaumeSeren** [comment]
Well it is nice that we agree on that release.

I will wait a bit more, to let involved people have a chance to respond.

**Comment by andir** [comment]
+1 for semantic versioning, signed commit/tag

**Comment by GuillaumeSeren** [comment]
Hey !
As we all agreed, I tagged (+signed) the 1.0.0 release 🍻 

Thanks again @teythoon for his work, and his open mind to let the community help him continue this useful project.

Let's open the merge window for the 1.1 🚀

**Comment by freeekanayaka** [comment]
Hey there @GuillaumeSeren, I was about to upload to PyPI however I noticed that setup.py doesn't provide a version, so the sdist command defaults to version "0.0.0".

I'd suggest to delete the tag, apply the diff below and re-create the tag.

Alternatively I could apply this diff locally and upload, but then the resulting tarball on PyPI would not *exactly* match this git repository.

PS: I've noticed I have no commit rights for this repository, could someone please grant them to me? Thanks!

```diff
diff --git a/setup.py b/setup.py
index 510646f..630d469 100755
--- a/setup.py
+++ b/setup.py
@@ -28,6 +28,7 @@ def get_requires():
 
 setup(
     name='afew',
+    version='1.0.0',
     packages=find_packages(),
     test_suite='afew.tests',
     package_data={
```

**Comment by GuillaumeSeren** [comment]
@freeekanayaka Hey good feedback I added it in #130 !

For the commit access we have to ask to @andir or @flokli

**Comment by freeekanayaka** [comment]
@GuillaumeSeren great, PyPI releaed pushed:

https://pypi.python.org/pypi/afew

I've added @flokli as Owner of the PyPI project (along with myself), if anybody else wants to step in please let us know :)

PS: @flokli mind granting me commit rights for this repo? cheers

**Comment by flokli** [comment]
@freeekanayaka already did. You've got mail ;-)

**Comment by GuillaumeSeren** [comment]
@freeekanayaka @flokli Nice feedback thank you 🍻
