### ISSUE TITLE
afew throws database error

### ISSUE THREAD

**Issue by three-comrades** [afewmail/afew#135]
I'm trying to run `afew` master (also tried 1.0) with `notmuch` 0.23.5 on Arch Linux. `notmuch` in combination with `alot` seems to work fine. But when I try to tag my files, I get:

    afew --tag --all
    terminate called after throwing an instance of 'Xapian::DatabaseCorruptError'
    Aborted (core dumped)

Any ideas what may be causing this?

**Comment by GuillaumeSeren** [comment]
Heyy @three-comrades 
can you elaborate your use case and give afew configuration.

But my guess is you DB is in bad shape
```
'Xapian::DatabaseCorruptError'
```

**Comment by three-comrades** [comment]
Hm, before, I deleted the notmuch database several times and created it from scratch and every time I got the same error. Today, I tried again and I don't get the error any more. I guess this isn't a bug in afew then, but something else must be wrong. Let me close this for now and sorry for the noise.
