### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#149]
Hey,
we have landed 30+ commits (during 4 month) since tag 1.0.0, I think we should prepare a new release,
if you want to wait more or anything else (broken feature) let us know !

**Comment by flokli** [comment]
Right, especially #148 was a pretty big change. I tagged the latest commit and released it as version 1.1.0, it's already uploaded to PyPI.

**Comment by GuillaumeSeren** [comment]
@flokli Great !
