### ISSUE TITLE
If List-Id has dots (".") the filter will not classify the message for 'lists'

### ISSUE THREAD

**Issue by mrvdb** [afewmail/afew#153]
Some (many?) lists have List-Id in the form  "topic.mail.company.com" 

Is there a specify reason for this?

**Comment by flokli** [comment]
This might be due to the fact that dots in tags look odd, but right, we should still match these kind of names inside angle brackets, but only use the part before the first dot as tag instead.

Could you modify the regex at https://github.com/afewmail/afew/blob/master/afew/filters/ListMailsFilter.py#L26 ?

**Comment by mrvdb** [comment]
> Could you modify the regex at
> https://github.com/afewmail/afew/blob/master/afew/filters/ListMailsFilter.py#L26
> ?

I copied the filter into the afew config folder and extended it
there. Having just the part before the dot might indeed be the best
generic solution, but I'm going to need a bit more.

It obviously depends on the lists, but in the format
'topic.mail.company.com' I personally would at least want to extract the
'company' bit for the tag.

**Comment by mrvdb** [comment]
Oh, I see https://tools.ietf.org/html/rfc2919 has a specific format requirements for List-ID headers. Seems that the lists involved actually have malformed 'List-ID' headers.

**Comment by flokli** [comment]
@mrvdb Didn't know that RFC, there are too many :-D
Could you still add a PR modifying the regex to match the first part, and maybe tests?

This would allow me to remove a lot of my custom tagging, as ListMailsFilter would then work ;-)

**Comment by mrvdb** [comment]
Excerpts from Florian Klink's message of juli 26, 2017 22:34:
> @mrvdb Didn't know that RFC, there are too many :-D
> Could you still add a PR modifying the regex to match the first part,
> and maybe tests?

Is that what we want, that is, matching a (basically) invalid header?

For the specific list which triggered this I filed a bug report here
https://github.com/odoo/odoo/issues/18408 but have little hope it will
lead to anything

I agree that it would save a lot of custom tagging.

If we are somewhat relaxed on the issue and are fine with matching
whatever comes along in List-Id, I can certainly make a PR for that :-)

**Comment by flokli** [comment]
I'd be fine in both tagging ```List-Id: community.mail.odoo.com``` and ```List-Id: Odoo Community <community.mail.odoo.com>``` with `community`, even though the first List-Id might be invalid according to RFC2919. Mails already exist using these headers, so we shouldn't make it ourselves harder than it is ;-)

We should regardless add some tests for this regex, to not introduce some unwanted behaviour.

I'm not sure about the 'getting multiple parts of the list-id' thing. Maybe a boolean argument, which if enabled would tag with community-mail-odoo-com, or a dict mapping tags to regexes matching whole list ids, with the current code as a fallback if nothing matched?

What are your thoughts?

**Comment by flokli** [comment]
Whatever floats your goat :-)
