### ISSUE TITLE
Error installing afew through pip on macOS

### ISSUE THREAD

**Issue by svmhdvn** [afewmail/afew#156]
I followed your installation guide in the README, but I get an error when I try to install `afew` with `pip`:

```
(.venv) bash-4.4$ pip install afew
Collecting afew
  Using cached afew-1.1.0.tar.gz
Collecting notmuch (from afew)
  Could not find a version that satisfies the requirement notmuch (from afew) (from versions: )
No matching distribution found for notmuch (from afew)
```

These are the versions of the relevant tools:
```
(.venv) bash-4.4$ pip --version
pip 9.0.1 from /Users/siva/.venv/lib/python3.6/site-packages (python 3.6)
(.venv) bash-4.4$ python --version
Python 3.6.2
(.venv) bash-4.4$ notmuch --version
notmuch 0.25
```

I installed notmuch through homebrew. Is there anything I'm missing that I need to install `afew` using `pip`?

**Comment by flokli** [comment]
It's looks pretty much like the notmuch python bindings are missing. Can you install those via homebrew, too?

**Comment by svmhdvn** [comment]
The notmuch brew formula didn't install python3 bindings by default, it only installed the python2 ones. I reinstalled with `brew install --with-python3 notmuch` and it worked! Thanks for the help.

**Comment by flokli** [comment]
No problem! Would you mind adding a section to the README, which explains installation via homebrew?

**Comment by svmhdvn** [comment]
Added, hopefully that's enough :)
