### ISSUE TITLE
Multiple accounts with afew

### ISSUE THREAD

**Issue by Grimscythe1983** [afewmail/afew#162]
One thing I am missing is to setup `afew` to move messages between folders after tagging. It all works fine with just one account under `~/Mail`, however, I want to operate on 3 separate accounts which would be `~/Mail/Account1` `~/Mail/Account2` `~/Mail/Account3`

How do I configure `afew` to move messages based on tags in specific accounts?

**Comment by flokli** [comment]
I do have a similar setup with multiple accounts, and add account-specific tags via `FolderNameFilter`.

I use a combination of server-side initial sorting via sieve, and afews `MailMover` to move mails matching a specific query to another folder (things like moving manually tagged junk to a junk folder). This should also work across accounts, as its just a separate maildir (although I didn't test that on my own)

Please see [the docs](http://afew.readthedocs.io/en/latest/move_mode.html) and report back if something is unclear.

**Comment by Grimscythe1983** [comment]
Ok I'll look into setting up `FolderNameFilter` this seems exactly what I am after. The docs lack an example of how to set this up for multiple accounts. It would be handy to have it there.

Thank you very much for your help!

**Comment by flokli** [comment]
```yaml
account1/INBOX: 'tag:foo':account2/foodir
```

should move all mails tagged with `foo` from `account1/INBOX` to `account2/foodir`.

**Comment by flokli** [comment]
@Grimscythe1983 In case you want to improve the documentation here, pull requests are warmly welcome :-)

**Comment by Grimscythe1983** [comment]
I am going to test the multiple account setup as soon as I'll get a chance and I'll write up some docs on that. No bother ;-)

**Comment by flokli** [comment]
Great, thanks!

**Comment by Grimscythe1983** [comment]
I am pleased to inform that the `FolderNameFilter` works like a charm. I should have some time over the weekend to create a section in the docs for that.
