### ISSUE TITLE
86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o     _posixsubprocess.c:3:20: fatal error: Python.h: No such file or directory     compilation terminated.     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by titoum** [afewmail/afew#176]
Hi ALL,
I'am trying to install matplotlib on my laptop lnux mint with python versio .2.7 but i always receive an orror for this. Could anyone help me please?

**Comment by andir** [comment]
How is this related to afew?

**Comment by GuillaumeSeren** [comment]
Hey @titoum please use a more informative title and describe you use case.

Beside that I don't where it is related to afew, I close this issue reopen if you more information.
