### ISSUE TITLE
dry-run not working

### ISSUE THREAD

**Issue by varac** [afewmail/afew#180]
At least in combination with `--move-mails`, `--dry-run` is not working as expected:

```
» afew --move-mails -vvvvvvvv --dry-run                                                                                                             
» afew --move-mails -vvvvvvvv          
Processed 2 total files in almost no time.
No new mail. Detected 2 file renames.

» afew --version
1.3.0
```

**Comment by GuillaumeSeren** [comment]
Hey @varac thank you for the feedback,
Yes I think it is a real issue, we should fix it asap.

**Comment by varac** [comment]
@GuillaumeSeren Please fix this, it's important for debugging, right now I'm really stabbing in the dark with no dry-run and no way to run in verbose mode (#181).

**Comment by GuillaumeSeren** [comment]
Hey @varac 
I understand your feedback and be sure that it is in my todo list,
but there is a lot of thing in there (+ everyday work).

So if you want this fast(-er) I suggest that you go ahead and do it on your own,
it would be helpful, and we could help / review when needed.

**Comment by GuillaumeSeren** [comment]
Hey @varac 
I have investigate a bit more about your problem, and on my setup the exact command you report 'afew --move-mails -vvvvvvvv --dry-run' is verbose and not move anything, here an example of the output
```sh
$ afew --version                                                                                                                                                                                                 1.3.0
$ afew --move-mails -vvvvvvvv --dry-run
INFO:root:    b'[2017-11-27 16:46:06] Jon Mason | Re: [GIT PULL] NTB bug fixes for v4.15'                                                                                                                                                     
INFO:root:from 'Perso/archive' to 'Perso/INBOX'                                                                                                                                                                                               
INFO:root:I would move mail                                                                                                                                                                                                                   
INFO:root:    b'[2017-11-27 16:41:24] Maxime Ripard | [PATCH v2 00/18] drm/sun4i: Add A83t LVDS support'                                                                                                                                      
INFO:root:from 'Perso/archive' to 'Perso/INBOX'                                                                                                                                                                                               
INFO:root:I would move mail                                                                                                                                                                                                                   
INFO:root:    b'[2017-11-27 16:32:02] Lorenzo Pieralisi | Re: [PATCH] PCI: designware-ep: Fix ->get_msi() to check MSI_EN bit'                                                                                                                
INFO:root:from 'Perso/archive' to 'Perso/INBOX'                                                                                                                                                                                               
INFO:root:I would move mail
```

And when i checked the MailMover classes there is a param to setup the dry-run mode, so first upgrade to latest master and reopen if the issue is still happening.

**Comment by GuillaumeSeren** [comment]
Hey @varac 
can you confirm the bug on the 1.3.0 as well ?

**Comment by GuillaumeSeren** [comment]
Maybe @flokli can confirm or not the issue on his setup ?

**Comment by flokli** [comment]
Just tested this here as well, and got some debug output as well, with `dry-run` being passed to mail mover as well.

As suggested in #181, please do some debugging on how far you get, and check your configuration.

**Comment by varac** [comment]
@flokli I finally found the issue!

I'm using latest master and can reproduce it installing using python2 (which uses `Python 2.7.15rc1` from ubuntu bionic), using: `python2 setup.py install --prefix=~/.local`

When I use python3 instead (`python3 setup.py install --prefix=~/.local`), it works fine!

**Comment by flokli** [comment]
Oh wow. I didn't dig into why python 2 has problems here, and personally use and encourage python 3 use everywhere possible.

Do you see a reason for why python2 is causing problems? Maybe we should just make `afew` python 3 only, given python 2 is pretty dead already anyhow…
