### ISSUE TITLE
Documentation bug : misleading text in filters.rst

### ISSUE THREAD

**Issue by jefftemplon** [afewmail/afew#207]
The text describing "ArchiveSentMailsFilter" says

It extends SentMailsFilter with the following feature:

I understand the intent, but the "extension" implies that ArchiveSentMailsFilter is an extended version of  SentMailsFilter.  This is not the case: for example, to_transforms works for SentMailsFilter but not this one. 

I suggest this alternate text:

If you don't want your sent mails to show up in your inbox, use this filter in addition to SentMailFilter. The 'new' tag will be removed from your sent emails (see SentMailsFilter for the definition of sent emails) by this filter.

**Comment by flokli** [comment]
@jefftemplon looking at the code, `ArchiveSentMailsFilter` is basically just calling `SentMailsFilter`, but additionally removing the notmuch new tags.

It's (only) missing `to_transforms`, as this variable is missing from `ArchiveSentMailsFilter.__init__`'s signature (and not passed down to `SentMailsFilter`)

I don't see a reason why it shouldn't.

**Comment by flokli** [comment]
I opened #225 which should fix this - could you test this?

**Comment by jefftemplon** [comment]
Hi,

no longer actively using afew / notmuch (except for archiving purposes), sorry!
