### ISSUE TITLE
new filter policy

### ISSUE THREAD

**Issue by igwan** [afewmail/afew#210]
What's your policy on new filters? Do you only want basic filters or is everyone welcome to make a pull request with it's new filter? What about filters that depends on external software/lib?

I'm asking because I made an user filter and I wonder if I should rewrite it as an internal filter and make a pull request.

**Comment by GuillaumeSeren** [comment]
Hello !
we already added new 'generic' filter so my answer is probably yes.
Based on 'external software/lib' it depends but I'd say probably no we could add a link to them in the doc btw.

Feel free to say more about your filter, so I could give more precise feedback.
I close, this issue you reopen it if you want to talk more about this.
