### ISSUE TITLE
Preparation of the v2 *WIP*

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#212]
Hey there,
I was away from the project for a while, but I still use it a lot,
and I think there is some big changes to be make to reach a v2.

Why v2 ?
Because python2 is coming to EOL in 1 year, and to do other bc breaking changes (refactor, tests),
we will need a new major version, so user can stay on the v1 branch as long as they want, and v2 could be a more fast moving branch.

Some of those changes have been waiting for a long time:

- Migrate the codebase to python3.
- Refactor the MailMover.
- Add unit test for the main codebase of afew.
- Add test data for each filter.

So obviously any help is welcome, and I will update this issue to keep the discussion open,
feel free to send you opinion about this.

Guillaume

**Comment by flokli** [comment]
Given Python 2 support was already dropped some time ago, we need to bump the major version before doing the next release anyhow.

Given that some features are simply broken with Python 2, and we never backported fixes into a Python 2 branch, I don't see much reason for maintaining a v1.x branch.

I did spend some time recently fixing some small issues, updated NEWS.md and cleaned up some Python 2 remains.

I intend to craft a release soon, and don't think we should do larger refactorings before that.

**Comment by GuillaumeSeren** [comment]
Hey @flokli 
I have followed your work and was a bit surpised by the python2 drop (as I used it for example),
so now that it is done I aggree you should tag a new major release.

And as this is major changes and I will wait a bit to push a MailMover refactor again.
