### ISSUE TITLE
Allow specifying different configuration

### ISSUE THREAD

**Issue by muradm** [afewmail/afew#237]
Currently `afew` reads only `.config/afew/config` file. While it could be possible to workaround by playing with `$XDG_CONFIG_HOME` environment variable, out-of-the-box-support would be more straight forward.

Why multiple configurations:
- managing multiple mailboxes
- having different sets of `MailMover` configurations

**Comment by GuillaumeSeren** [comment]
Hey,
I think it is pretty much a duplicate of #236, as the actual implementation might need some work to work well, there is not problem to support multiple config file (and notmuch databases).

I close in favor of #236 feel free to re-open if needed.

**Comment by igoralmeida** [comment]
So the idea is to both fix `-C` (the problem in #236) AND add another flag to specify which afew configuration file should be used (this issue) in the same pull request?
