### ISSUE TITLE
(Archive)SentMailsFilter doesn't work if there's an extra ';' in notmuch-config

### ISSUE THREAD

**Issue by TimQuelch** [afewmail/afew#265]
If there is a trailing semicolon in the notmuch-config the sent mails filter will not work e.g. 
```
primary_email=primary@domain.com
other_email=secondary@domain.com;tertiary@domain.com;
```
This looks like it is because the `other_email` option is handled by 
```python
for other_email in notmuch_settings.get('user', 'other_email').split(';'):
    my_addresses.add(other_email)
```
which (I think) will add an empty string onto the end. Later when the query is built this empty string will result in no emails being matched.

This could be fixed by a simple empty string check in that for loop. However it might be beneficial to adjust the behaviour of `notmuch_settings.get()` to remove any trailing ';' to eliminate any similar bugs.

**Comment by GuillaumeSeren** [comment]
Hello @TimQuelch thank you for this issue.

After reading you issue, I did some digging on it, and you right,
the usage of 'split()' in this case produce a blank entry at the end.

Let's talk about the patch in the PR.
