### ISSUE TITLE
Where to discuss usage questions?

### ISSUE THREAD

**Issue by rkrug** [afewmail/afew#44]
Hi

I started using afew and it is REALLY nice. But I still have a few question on how to change some rules (mailing list identification). I guess the "issues: section is not the best place to ask.

Is there a mailing list I could use to ask ask or should I mail you directly?

Thanks,

Rainer

**Comment by flokli** [comment]
I created a channel #afewmail on freenode, as I didn't want to spam the #notmuch channel with too much afew-related questions. Feel free to join :-)
