### ISSUE TITLE
example for static filter in sample config is wrong

### ISSUE THREAD

**Issue by dbp** [afewmail/afew#56]
The sample config, which is the only place I can find reference to a static filter, has this:

```
# [Filter.1]
# query = from:boss@office.com
# tag = +office
```

Which I banged my head against for a while, until I saw #22 and saw in the comments that it has to be "tags", not "tag". 

In general, I think the documentation on this could be improved - it seems a little bit crazy that there isn't an example of a static filter in the documentation page on filters!

**Comment by intrigeri** [comment]
Looks like this issue could be closed, the doc has been fixed a while ago..

**Comment by GuillaumeSeren** [comment]
Hey there,
as this was merged quite a while ago this issue should be close.
