### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by d0ugal** [afewmail/afew#83]
Is there a reason this isn't listed on pypi?

**Comment by mkaito** [comment]
:+1: 

I'd love to manage afew using [pipsi](https://github.com/mitsuhiko/pipsi), a handy virtualenv manager for python programs. Because not using virtualenv just leads to pain.

This requires that afew be on PyPI.

**Comment by ryneeverett** [comment]
```console
pipsi install git+https://github.com/teythoon/afew.git#egg=afew 
```

**Comment by GuillaumeSeren** [comment]
Hey,
on the pypi subject I think beside it needs notmuch to be installed on the system,
I think it is possible to add the package the last release in PyPI,
I didn't done it before but I guess it can done quite easily.

**Comment by flokli** [comment]
We did a release on PyPI, so this can be closed now :-)
