### ISSUE TITLE
how to --learn that something is _not_ classified in a category

### ISSUE THREAD

**Issue by ibotty** [afewmail/afew#92]
canonical example might be ham vs spam. but it happens more often with categories that are not as big.

**Comment by mkaito** [comment]
I would like to know this as well. Because I've somehow managed to teach afew to put every category I've taught it into all of my emails.

**Comment by teythoon** [comment]
I'm sorry about that.  While I still feel like doing some kind of machine learning would be super nice in a tool like afew, what I implemented back then was misguided.  I don't really think it works at all.

**Comment by mkaito** [comment]
Oh well. I thought I had taught afew wrong or something. Whenever I try to create a new category, it applies to every single mail in my account.

**Comment by dannyob** [comment]
Maybe this should be removed if it doesn't work?

**Comment by kyrias** [comment]
At the very least removed from the README and such, hm.  I might try to look into rewriting it though, because it'd be quite handy to have.

**Comment by flokli** [comment]
@kyrias I also don't use this feature. Would you mind filing a PR removing code and parts from the README? If this feature gets reimplemented, it might be good to start from scratch - the old code is still in the git history…

**Comment by agrudzinsky** [comment]
Can you, please, make a note in README that this feature is removed on ... date starting version ...?  There are plenty of blogs and places on the Internet that mention this feature and this is the only place I found mentioning that it has been removed.  Most notably, it is mentioned on https://notmuchmail.org/initial_tagging/:

> afew is an initial tagging solution that should work out of the box for most basic tagging needs (mailinglist handling, killed thread handling, autoarchiving of sent mails) and has some fancy features (e.g. mail classification using bayesian filters).

A change log does not seem to be a part of documentation.  I spent a fair amount of time searching the documentation in vain.  GitHub does not show closed issues by default.  So, finding this notice is difficult.  It would save time for new users like me.  Thanks.

**Comment by agrudzinsky** [comment]
Also, is creating `~/.local/share/afew/categories` still relevant or does it need to be removed from the "Initial Config section of the documentation?

<blockquote>
Initial Config
Create the directories to hold the config files:

$ mkdir -p ~/.config/afew ~/.local/share/afew/categories
</blockquote>

**Comment by flokli** [comment]
@agrudzinsky release notes are currently lacking - and indeed, it would have made sense to have that added to a changelog (if we had one)… - I added https://github.com/afewmail/afew/issues/223 to get this sorted out eventually, but can't promise a quick resolution due to lack of time.

I removed the mail classification mentions from the notmuch website, and the line about `~/.local/share/afew/categories` from the docs - thanks for spotting this!
