### ISSUE TITLE
challenges with docs: Extending afew 

### ISSUE THREAD

**Issue by shagol** [afewmail/afew#93]
Hi,

https://afew.readthedocs.org/en/latest/extending.html

I followed the example above to extend afew but ran into some issues with the import statements and getting the filter to register.

In the end I got this to work

from afew.FilterRegistry import register_filter
from afew.filters.BaseFilter import Filter

**Comment by GuillaumeSeren** [comment]
hey @shagol 
I am late to this party, but does this still an issue today ?

As this issue is quite old, and not really precise I close it feel free to reopen if this still apply
