### ISSUE TITLE
missing categories directory causes all mail to be flagged

### ISSUE THREAD

**Issue by mturquette** [afewmail/afew#94]
When upgrading my Linux distro I migrated all of my mail, notmuch database and my offlineimap/afew/alot toolchain successfully from the old distro to the new with the minor exception that I somehow managed to remove ~/.local/share/afew/categories.

This caused 90% of my mail (both old and new) to get tagged as "flagged" by afew. Over 9000 messages in total. I added back the empty categories directory, removed all instances of the "tagged" flag with,

```
notmuch tag -flagged "*"
```

And now things are working again. Seems like afew should fail more gracefully in the absence of the categories directory even output some error.

**Comment by adborden** [comment]
Since the classifier filter is no longer supported, I think this can be closed. Without the filter, this shouldn't be a issue.

**Comment by mturquette** [comment]
Agreed, thanks.
