### ISSUE TITLE
MailMover.py crashes if mail was deleted 

### ISSUE THREAD

**Issue by J-N-K** [afewmail/afew#98]
Running afew --move-mail crashes if one of the files in the notmuch database was previously deleted. This is due to the exception handling in Mailmover.py The shutil-Copy routine (l. 75) raises an exception if the file was not found and the exception-handler only takes care of "already exists" errors. 

If the file was not found, it should be reported but not crash afew.

**Comment by flokli** [comment]
@GuillaumeSeren Can you check if #189 properly handles this? We should probably `logger.warn`, but then skip over that file.

**Comment by GuillaumeSeren** [comment]
Hello @floki @J-N-K,
as the refactored version of the MailMover (still welcome feedback on this patch !! :beer),
is more iterative and do a process of moving on a mail centric way before we do the whole list at once.

I think this could fix, you issue, please test the MailMover and add your feedback.

**Comment by J-N-K** [comment]
I‘m not using afew any longer, so i can‘t test. Sorry.
